#!/bin/sh
export BRANCHNAME=$(git rev-parse --abbrev-ref HEAD)
export MASTER_SHA1=$(git rev-parse master)
export SHA1=$(git rev-parse fuzzer)
export GITHUB_URL=$(git config --get remote.origin.url | sed 's/.git$//')
export JENKINS_IP={{HOST_IP}}

if [ $BRANCHNAME = 'master' ]; then
        curl "http://$JENKINS_IP:8080/git/notifyCommit?url=$GITHUB_URL&branches=fuzzer&sha1=HEAD"
        node fuzzer.js
fi
